### ISSUE TITLE
Getting an error when building the initramfs

### ISSUE THREAD

**Issue by sunflsks** [abelian424/archiso-bcachefs-mainline#3]
Whenever the initramfs is getting built, I'm getting an error saying that a bunch of modules have not been found, and then the whole script exits. Here's exactly what's happening:

Starting build: 5.6.14-1-mainline-bcachefs
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [memdisk]
ERROR: module not found: phram'
 ERROR: module not found:mtdblock'
  -> Running build hook: [archiso_shutdown]
  -> Running build hook: [archiso]
 ERROR: module not found: cdrom'
 ERROR: module not found: dm_snapshot'
 ERROR: module not found: `overlay'
  -> Running build hook: [archiso_loop_mnt]
  -> Running build hook: [archiso_pxe_common]
  -> Running build hook: [archiso_pxe_nbd]
 ERROR: module not found: nbd'
  -> Running build hook: [archiso_pxe_http]
  -> Running build hook: [archiso_pxe_nfs]
 ERROR: module not found: nfs'
  -> Running build hook: [archiso_kms]
 ERROR: module not found: radeon'
 ERROR: module not found: nouveau'
 ERROR: module not found: via_agp'
 ERROR: module not found: sis_agp'
 ERROR: module not found: intel_agp'
  -> Running build hook: [block]
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
 Generating module dependencies
 Creating xz-compressed initcpio image: /boot/archiso.img
 WARNING: errors were encountered during the build. The image may not be complete.

**Comment by abelian424** [comment]
This really looks like a problem with your mkinitcpio config, not the
program. It shouldn't look for those modules unless if your config tells it
to.

**Comment by abelian424** [comment]
Couldn't reproduce it. Really think it's the mkinitcpio config.
