### ISSUE TITLE
error with make_iso.sh

### ISSUE THREAD

**Issue by erg** [abelian424/archiso-bcachefs-mainline#4]
``archiso-bcachefs-mainline-5.6``

Also it looks like it's trying whatever the latest linux is instead of 5.6?

```
...
==> Validating source files with md5sums...
    linux-5.7.8.tar.xz ... Passed
    linux-5.7.8.tar.sign ... Skipped
    config ... Passed
    0000-sphinx-workaround.patch ... Passed
    0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Passed
    0002-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ... Passed
    0003-Revert-ath9k-Fix-general-protection-fault-in-ath9k_h.patch ... Passed
    0004-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ... Passed
    0002-clear-patches.patch ... Passed
    0003-glitched-base.patch ... FAILED
    0006-add-acs-overrides_iommu.patch ... Passed
    0007-v5.7-fsync.patch ... Passed
    0008-5.7-bcachefs.patch ... Passed
    PATCH-RFC-x86-mm-pat-Restore-large-pages-after-fragmentation.mypatch ... FAILED
    Reduce-lock-contention-on-swap-cache-from-swap-slots-allocation.mypatch ... FAILED
    The-new-cgroup-slab-memory-controller.mypatch ... FAILED
    async_buffered_reads.mypatch ... FAILED
    mm_proactive_compaction.mypatch ... FAILED
    workingset_protection.mypatch ... FAILED
    zstd.mypatch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by abelian424** [comment]
I usually use the CK package, but I'll update this one to work with 5.7.
the problem is the failed patch is 5.6 version.

**Comment by abelian424** [comment]
I updated with a generic linux-mainline-bcachefs version. It will
automatically download the latest kernel and patches according to the
PKGBUILD

**Comment by erg** [comment]
I also tried CK and it had a similar error. Will try this later, thanks!

**Comment by erg** [comment]
I am probably doing something wrong here.

```
➜  archiso-bcachefs-mainline-5.6 git:(master) ✗ pwd
/home/foobar/archiso-bcachefs-mainline/archiso-bcachefs-mainline-5.6
➜  archiso-bcachefs-mainline-5.6 git:(master) ✗ chmod a+x make_iso.sh
➜  archiso-bcachefs-mainline-5.6 git:(master) ✗ ./make_iso.sh 
...
...
==> Validating source files with md5sums...
    linux-5.7.9.tar.xz ... Passed
    linux-5.7.9.tar.sign ... Skipped
    config ... Passed
    0000-sphinx-workaround.patch ... Passed
    0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Passed
    0002-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ... Passed
    0003-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ... Passed
    0004-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ... Passed
    0002-clear-patches.patch ... Passed
    0003-glitched-base.patch ... FAILED
    0006-add-acs-overrides_iommu.patch ... Passed
    0007-v5.7-fsync.patch ... Passed
    0008-5.7-bcachefs.patch ... Passed
    PATCH-RFC-x86-mm-pat-Restore-large-pages-after-fragmentation.mypatch ... FAILED
    Reduce-lock-contention-on-swap-cache-from-swap-slots-allocation.mypatch ... FAILED
    The-new-cgroup-slab-memory-controller.mypatch ... FAILED
    async_buffered_reads.mypatch ... FAILED
    mm_proactive_compaction.mypatch ... FAILED
    workingset_protection.mypatch ... FAILED
    zstd.mypatch ... FAILED
==> ERROR: One or more files did not pass the validity check!
➜  archiso-bcachefs-mainline-5.6 git:(master) ✗


➜  archiso-bcachefs-mainline-5.6 git:(master) ✗ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   make_iso.sh
	deleted:    packages/linux-mainline-bcachefs/0007-v5.6-fsync.patch
	modified:   packages/linux-mainline-bcachefs/PKGBUILD
	modified:   packages/linux-mainline-bcachefs/config
	deleted:    packages/linux-mainline-bcachefs/linux.install
	deleted:    packages/linux-mainline-bcachefs/sphinx-workaround.patch

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	archlive/
	packages/bcachefs-tools-git/
	packages/libscrypt/
	packages/linux-mainline-bcachefs/.SRCINFO
	packages/linux-mainline-bcachefs/.gitignore
	packages/linux-mainline-bcachefs/linux-5.7.9.tar.sign

no changes added to commit (use "git add" and/or "git commit -a")

```

**Comment by abelian424** [comment]
You could just delete the packages folder as well. The script downloads the
files if it doesn't find them. The AUR package works so I don't know what's
wrong.

**Comment by erg** [comment]
It's the checksums in the ``PKGBUILD`` file that are not letting it build.

This gets it past that step.
```
diff --git a/linux-mainline-bcachefs/PKGBUILD b/linux-mainline-bcachefs/PKGBUILD
index 0260229..e356f39 100644
--- a/linux-mainline-bcachefs/PKGBUILD
+++ b/linux-mainline-bcachefs/PKGBUILD
@@ -116,17 +116,18 @@ md5sums=('09d5fc3f89c9c0e607af7b0b0344b480'
          '2ef13b0799bd9b9b994389907812e7a7'
          'a85456a71ff92afb326f48363757d257'
          'b10e4c612d5240d66fad8f1c50fe3242'
-         '3159befb77cc65566196c205c2fe305c'
+         'a22cddcadc0da933dac13a6ab49b7ed9'
          '168a924c7c83ecdc872a9a1c6d1c8bdb'
          '228b33d0cb13cab162b3e051ec9bb88d'
          '0633bf8f7561c6903b445ff476815dc0'
-         '38b2dbf9094d5dd55a918ae45d30a198'
-         '90366b8f4ff2f0e74785b18346d4f8b1'
-         '7a269ee82e1172c57a34d1e291dbf1e5'
-         '4b08bc4ef6b3e5b1905b14376bf460c8'
-         'fcd3ce66f9ab3f1a4c7a06520d02f3c9'
-         '471dbe6647dcaebdd47bbd222547cd3e'
-         'd1828d13acd27e899c16a2a025d5d0d4')
+         'a4f52166d82a1c420e78613463d48fd4'
+         '92d69c5052ab9c2efff2bb46878adc11'
+         'e9f0ee15b2cc7014b9d11743277e7e31'
+         'e116270127851c48e1f05deabfd7b417'
+         '50132953068dec14608448c3a9b69731'
+         '35b3025b6d3c402e0cfc0b15ca350978'
+         '7c24d163cc35eb34ed1dcc920a583d98')
+
 
 export KBUILD_BUILD_HOST=archlinux
 export KBUILD_BUILD_USER=$pkgbase
```

**Comment by abelian424** [comment]
Yeah, the old PKGBUILD's are outdated. The shell script will download the
latest AUR packages if it finds the packages directory empty though. I
should still update to make it painless though.

**Comment by erg** [comment]
I deleted the packages directory and it still doesn't do the right thing.

```
git clone
cd archiso-bcachefs-mainline/archiso-bcachefs-mainline-5.6
pwd
    /home/erg/archiso-bcachefs-mainline/archiso-bcachefs-mainline-5.6
rm -rf packages
chmod a+x make_iso.sh
./make_iso.sh
....
...


==> Validating source files with md5sums...
    linux-5.7.9.tar.xz ... Passed
    linux-5.7.9.tar.sign ... Skipped
    config ... Passed
    0000-sphinx-workaround.patch ... Passed
    0001-ZEN-Add-sysctl-and-CONFIG-to-disallow-unprivileged-C.patch ... Passed
    0002-PCI-EDR-Log-only-ACPI_NOTIFY_DISCONNECT_RECOVER-even.patch ... Passed
    0003-iwlwifi-Make-some-Killer-Wireless-AC-1550-cards-work.patch ... Passed
    0004-virt-vbox-Add-support-for-the-new-VBG_IOCTL_ACQUIRE_.patch ... Passed
    0002-clear-patches.patch ... Passed
    0003-glitched-base.patch ... FAILED
    0006-add-acs-overrides_iommu.patch ... Passed
    0007-v5.7-fsync.patch ... Passed
    0008-5.7-bcachefs.patch ... Passed
    PATCH-RFC-x86-mm-pat-Restore-large-pages-after-fragmentation.mypatch ... FAILED
    Reduce-lock-contention-on-swap-cache-from-swap-slots-allocation.mypatch ... FAILED
    The-new-cgroup-slab-memory-controller.mypatch ... FAILED
    async_buffered_reads.mypatch ... FAILED
    mm_proactive_compaction.mypatch ... FAILED
    workingset_protection.mypatch ... FAILED
    zstd.mypatch ... FAILED
==> ERROR: One or more files did not pass the validity check!
```

**Comment by abelian424** [comment]
This is weird. I uploaded the latest  version and deleted the old versions.
I couldn't test it as the AUR was down yesterday but I will check it when I
get home.

**Comment by abelian424** [comment]
Thanks for letting me know this problem. Easy mistake, I haven't been deleting the mypatch files when I update the AUR package so the file hashes are mismatched. I fixed the AUR mistake when I updated to 5.7.10

**Comment by abelian424** [comment]
Ok, I fixed it by just skipping the checksums for the .mypatch files. I don't know why this glitch happens, as downloading from the AUR works fine. Thanks for letting me know about this problem.

**Comment by abelian424** [comment]
For some reason, even though the AUR package install fine with an AUR helper, it fails validity check using the script. So I've just disabled the .mypatch files for the PKGBUILD. You can still manually reenable them and updpkgsum if you need. Thanks for having patience, I really didn't see what the problem was at first.

**Comment by abelian424** [comment]
> It's the checksums in the `PKGBUILD` file that are not letting it build.
> 
> This gets it past that step.
> 
> ```
> diff --git a/linux-mainline-bcachefs/PKGBUILD b/linux-mainline-bcachefs/PKGBUILD
> index 0260229..e356f39 100644
> --- a/linux-mainline-bcachefs/PKGBUILD
> +++ b/linux-mainline-bcachefs/PKGBUILD
> @@ -116,17 +116,18 @@ md5sums=('09d5fc3f89c9c0e607af7b0b0344b480'
>           '2ef13b0799bd9b9b994389907812e7a7'
>           'a85456a71ff92afb326f48363757d257'
>           'b10e4c612d5240d66fad8f1c50fe3242'
> -         '3159befb77cc65566196c205c2fe305c'
> +         'a22cddcadc0da933dac13a6ab49b7ed9'
>           '168a924c7c83ecdc872a9a1c6d1c8bdb'
>           '228b33d0cb13cab162b3e051ec9bb88d'
>           '0633bf8f7561c6903b445ff476815dc0'
> -         '38b2dbf9094d5dd55a918ae45d30a198'
> -         '90366b8f4ff2f0e74785b18346d4f8b1'
> -         '7a269ee82e1172c57a34d1e291dbf1e5'
> -         '4b08bc4ef6b3e5b1905b14376bf460c8'
> -         'fcd3ce66f9ab3f1a4c7a06520d02f3c9'
> -         '471dbe6647dcaebdd47bbd222547cd3e'
> -         'd1828d13acd27e899c16a2a025d5d0d4')
> +         'a4f52166d82a1c420e78613463d48fd4'
> +         '92d69c5052ab9c2efff2bb46878adc11'
> +         'e9f0ee15b2cc7014b9d11743277e7e31'
> +         'e116270127851c48e1f05deabfd7b417'
> +         '50132953068dec14608448c3a9b69731'
> +         '35b3025b6d3c402e0cfc0b15ca350978'
> +         '7c24d163cc35eb34ed1dcc920a583d98')
> +
>  
>  export KBUILD_BUILD_HOST=archlinux
>  export KBUILD_BUILD_USER=$pkgbase
> ```

I could add this patch to manually update the checksums, but I would have to update it each time the .mypatch changes. If you guys want that, let me know.

**Comment by erg** [comment]
Have you tried this on a fresh repository? It still didn't work for me.

**Comment by abelian424** [comment]
I opened an issue for this. The workaround is that your linux bcachefs
kernel should already be pre-built in the packages directory. Then the ISO
builds fine. Also, check if you have dracut as that might cause unforeseen
problems (purely from anecdote however).
