### ISSUE TITLE
Scripts do not work with latest versions of Archiso

### ISSUE THREAD

**Issue by Hamled** [abelian424/archiso-bcachefs-mainline#7]
Some time earlier this year the Archiso team decided to move away from the build.sh scripts in favor of a [profile-based approach](https://gitlab.archlinux.org/archlinux/archiso/-/issues/29).

As part of that work the `build.sh` script files were removed in October and are no longer present in the latest releases of the project. Since the `make_iso.sh` scripts in this project rely upon patching those files they no longer work correctly.

I was able to manually create a custom profile using the new [Archiso instructions](https://wiki.archlinux.org/index.php/Archiso#Prepare_a_custom_profile) for a variant of this project (I used `linux-bcachefs-git` instead of `linux-mainline-bcachefs` because that's what I run on my machine).

It seems very likely that the `make_iso.sh` script could be updated to automate the process of building a custom profile, and the remainder of the code for downloading and building the necessary packages could remain the same.

**Comment by abelian424** [comment]
I will look at fixing it this weekend. Hopefully it doesn't eat up my whole day.

**Comment by abelian424** [comment]
> I will look at fixing it this weekend. Hopefully it doesn't eat up my whole day.

Well, that never happened. I don't have an excuse except for being too busy or tired. I'm going through the make_iso.sh process now. Simply commenting out the part that uses build.sh lets the script run, but I will have to see if this omits any vital files.

**Comment by abelian424** [comment]
Update: I need to review the new system. The only real changes in the script is to add the bcachefs kernel and supporting files to the base system, and I need to find a way to add them the new way. As of now, commenting out the build.sh references just builds a standard arch live iso.

**Comment by abelian424** [comment]
Fixed the issue. The new mkarchiso command is actually easier than I thought it would be, so I'm extra sorry it took over a month - I really haven't been giving this repo the care it deserves.

**Comment by Hamled** [comment]
No worries, thanks for working on it!
