### ISSUE TITLE
systemd-boot config is not changed

### ISSUE THREAD

**Issue by derlaft** [abelian424/archiso-bcachefs-mainline#8]
As a result, a standard linux kernel is loaded when this image is booted in UEFI mode.

**Comment by abelian424** [comment]
Both kernels are bootable, but the vanilla linux kernel is set as default. I don't see any any mkarchiso option to mess with systemd-boot options, and I haven't tried any sed hacks to alter the output of the config files. For now, you just have to choose the bcachefs kernel at boot (on my setup it was the third line).

**Comment by derlaft** [comment]
>or now, you just have to choose the bcachefs kernel at boot (on my setup it was the third line).

There's no such option in systemd-boot, at least for me. I guess you are seeing it in legacy mode, or something is different for me. The only way to boot the kernel is manually via UEFI shell option.

**Comment by abelian424** [comment]
I'm booting in UEFI mode but with Secure Boot turned off. For me each kernel is listed as an entry. You can also edit the loader/loader.conf file in your USB root folder. Change the default to archiso-x86_64.conf instead of archiso-x86_64-linux.conf and the bcachefs kernel will boot. I'll look at automating this, but I'm really not very good at this (coding is not my profession).

**Comment by derlaft** [comment]
>For me each kernel is listed as an entry. 

There is no option for bcachefs kernel for me:

```
% find archlive/efiboot/loader 
archlive/efiboot/loader
archlive/efiboot/loader/entries
archlive/efiboot/loader/entries/archiso-x86_64-speech-linux.conf
archlive/efiboot/loader/entries/archiso-x86_64-linux.conf
archlive/efiboot/loader/loader.conf
```
>You can also edit the loader/loader.conf file in your USB root folder.

It is not an easy thing to do, since it's a read-only ISO image

**Comment by abelian424** [comment]
The kernel appears I believe once the ISO is built with mkinitcpio. I assume you're writing to a USB drive not a CD so once you copy the ISO files to the USB drive root directory you can change the config. I'll look into adding a command into the script that overwrites the default systemd-boot config.
